import { BusinessRule } from './types'

export const DEFAULT_RULES: BusinessRule[] = [
  {
    id: 'rule-1',
    name: 'Desconto Progressivo por Quantidade',
    description: 'Desconto escalonado baseado na quantidade total de itens no pedido',
    type: 'PROGRESSIVE',
    enabled: true,
    priority: 'HIGH',
    discountType: 'PERCENTAGE',
    discountValue: 0,
    progressiveTiers: [
      { threshold: 100, discountValue: 3 },
      { threshold: 500, discountValue: 5 },
      { threshold: 1000, discountValue: 8 },
      { threshold: 5000, discountValue: 12 },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    appliedCount: 0,
  },
  {
    id: 'rule-2',
    name: 'Desconto à Vista',
    description: '5% de desconto para pagamentos à vista',
    type: 'CASH_DISCOUNT',
    enabled: true,
    priority: 'MEDIUM',
    discountType: 'PERCENTAGE',
    discountValue: 5,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    appliedCount: 0,
  },
  {
    id: 'rule-3',
    name: 'Frete Grátis acima de R$ 5.000',
    description: 'Frete grátis para pedidos acima de R$ 5.000,00',
    type: 'FREE_SHIPPING',
    enabled: true,
    priority: 'MEDIUM',
    discountType: 'PERCENTAGE',
    discountValue: 0,
    freeShippingThreshold: 5000,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    appliedCount: 0,
  },
  {
    id: 'rule-4',
    name: 'Desconto Máximo Global',
    description: 'Limite o desconto total a 15% do valor do pedido',
    type: 'MAX_DISCOUNT',
    enabled: true,
    priority: 'CRITICAL',
    discountType: 'PERCENTAGE',
    discountValue: 15,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    appliedCount: 0,
  },
  {
    id: 'rule-5',
    name: 'Promoção Cimento',
    description: '8% de desconto em todos os produtos da categoria Cimento',
    type: 'CATEGORY_PROMO',
    enabled: false,
    priority: 'LOW',
    discountType: 'PERCENTAGE',
    discountValue: 8,
    productFilter: { category: 'Cimento' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    appliedCount: 0,
  },
  {
    id: 'rule-6',
    name: 'Cliente VIP',
    description: '3% de desconto adicional para clientes VIP',
    type: 'CUSTOMER_VIP',
    enabled: true,
    priority: 'MEDIUM',
    discountType: 'PERCENTAGE',
    discountValue: 3,
    customerFilter: { isVip: true },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    appliedCount: 0,
  },
]
